[package]
name = "aggregator"
type = "bin"
authors = ["OneProof"]
compiler_version = ">=1.0.0"

[dependencies]
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v0.87.0", directory = "barretenberg/noir/bb_proof_verification" }
