#!/usr/bin/env bash
# Tier 3 portability - run the Tier 1 batch-track Groth16 proof through an
# EVM Solidity verifier (auto-generated by snarkjs from the SAME zkey we
# deployed to Stellar). forge test --gas-report gives us the EVM gas cost,
# which we compare against the Stellar fee in bench/results.json.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EVM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO="$(cd "$EVM_DIR/.." && pwd)"
CIRCUIT="$REPO/circuits/groth16_batch"

export NVM_DIR="$HOME/.nvm"
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use 22 >/dev/null 2>&1 || true
export PATH="$HOME/.foundry/bin:$HOME/.local/bin:$PATH"

echo "=== forge $(forge --version | head -1) / snarkjs $(npm ls -g snarkjs --depth=0 2>/dev/null | grep snarkjs | awk -F'@' '{print $2}') ==="

# ────────────────────────────────────────────────────────────────────────────
echo
echo "=== [1/4] generate Verifier.sol from Tier 1 zkey ==="
mkdir -p "$EVM_DIR/src" "$EVM_DIR/test"
snarkjs zkey export solidityverifier \
  "$CIRCUIT/target/circuit_final.zkey" \
  "$EVM_DIR/src/Verifier.sol"
echo "    wrote $EVM_DIR/src/Verifier.sol ($(wc -l < "$EVM_DIR/src/Verifier.sol") lines)"

# ────────────────────────────────────────────────────────────────────────────
echo
echo "=== [2/4] export Solidity calldata from the SAME proof we verified on Stellar ==="
# snarkjs emits hex values wrapped in quotes (e.g. ["0x...","0x..."]) which
# Solidity won't implicitly convert from string[2] to uint256[2]. Strip the
# quotes to get raw hex literals that Solidity accepts as uint256.
CALLDATA_RAW="$(snarkjs zkey export soliditycalldata \
  "$CIRCUIT/target/public.json" \
  "$CIRCUIT/target/proof.json")"
CALLDATA="$(echo "$CALLDATA_RAW" | tr -d '"')"
echo "    calldata length: ${#CALLDATA} chars (quotes stripped)"
echo "$CALLDATA" > "$EVM_DIR/.calldata"

# ────────────────────────────────────────────────────────────────────────────
echo
echo "=== [3/4] write test/Verifier.t.sol that calls verifyProof with the calldata ==="
# The Solidity verifier from snarkjs exports a function called verifyProof
# with signature: verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[k] input)
# returns (bool). The snarkjs calldata is a single line with comma-separated
# argument groups in the right order — paste verbatim.
cat > "$EVM_DIR/test/Verifier.t.sol" <<EOF
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Verifier.sol";

contract VerifierTest is Test {
    Groth16Verifier verifier;

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    function test_verifyTier1ProofOnEvm() public view {
        // Auto-generated calldata from the Tier 1 sanity proof (snarkjs
        // groth16 prove of circuits/groth16_batch/circuit.circom).
        // This is the SAME proof bytes that verified on Stellar testnet
        // in tx 99b168d8dae99328021fddcf4ab0889ae8916fa02b834f90e88d5a2fd1e3350d.
        bool ok = verifier.verifyProof(
            ${CALLDATA}
        );
        assertTrue(ok, "Tier 1 Groth16 proof MUST verify on EVM (same BN254)");
    }
}
EOF
echo "    wrote $EVM_DIR/test/Verifier.t.sol"

# ────────────────────────────────────────────────────────────────────────────
echo
echo "=== [4/4] forge build + forge test --gas-report ==="
cd "$EVM_DIR"
mkdir -p lib

# Install forge-std (needed for Test.sol). Use git submodule-style fetch.
if [ ! -d lib/forge-std ]; then
  echo "    fetching forge-std..."
  git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
fi

forge build
forge test --gas-report

echo
echo "=== TIER 3 EVM PORTABILITY GREEN ==="
echo "    Same Tier 1 Groth16 proof verified on both Stellar (testnet) and EVM (local Foundry)."
